cas:
  #Required properties
  server-url-prefix: https://dk.example.org:8143/cas
  server-login-url: https://dk.example.org:8143/cas/login
  client-host-url: https://dk.example.org:8443

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #gateway: true
  #use-session: false
  #redirect-after-validation: false
  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true


spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config. Change as appropriate for your local deployment environment
server:
  port: 8443
  ssl:
    enabled: true
    key-store: /Users/dima767/.keystore
    key-store-password: changeit
    trust-store: /Users/dima767/.keystore
    trust-store-password: changeit
  #For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  #context-parameters.renew: true


logging.level:
    org.jasig.cas: DEBUG
